services:
  - type: cron
    name: ogpn-bot-v2-render
    runtime: docker
    dockerfilePath: ./Dockerfile
    schedule: "*/6 * * * *"
    envVars:
      - key: OGPN_API_URL
        value: https://bot.ogpn.eu/2.0/api
      - key: OGPN_API_TOKEN
        sync: false
      - key: OGPN_WORKER_ID
        value: render-1
