name: OGPN-BOT worker
on:
  schedule:
    - cron: '7,27,47 * * * *'
  workflow_dispatch:
jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: {php-version: '8.4', extensions: curl}
      - run: php worker/run.php
        env:
          OGPN_API_URL: https://bot.ogpn.eu/2.0/api
          OGPN_API_TOKEN: ${{ secrets.OGPN_API_TOKEN }}
          OGPN_WORKER_ID: github-1
